version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - usermobile1
      - usermobile2
      - useremail1
      - useremail2
      - useraddress1
      - useraddress2
    networks:
      - webnet

  usermobile1:
    build: ./backend/mobile-service
    container_name: usermobile1
    environment:
      - DB_HOST=${Mysql_host}
      - DB_USER=${MySql_Db_User}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_Name=${MySql_Db}
    depends_on:
      - mysql
    networks:
      - webnet

  usermobile2:
    build: ./backend/mobile-service
    container_name: usermobile2
    environment:
      - DB_HOST=${Mysql_host}
      - DB_USER=${MySql_Db_User}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_Name=${MySql_Db}
    depends_on:
      - mysql
    networks:
      - webnet

  useremail1:
    build: ./backend/email-service
    container_name: useremail1
    environment:
      - DB_HOST=${Mysql_host}
      - DB_USER=${MySql_Db_User}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_Name=${MySql_Db}
    depends_on:
      - mysql
    networks:
      - webnet

  useremail2:
    build: ./backend/email-service
    container_name: useremail2
    environment:
      - DB_HOST=${Mysql_host}
      - DB_USER=${MySql_Db_User}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_Name=${MySql_Db}
    depends_on:
      - mysql
    networks:
      - webnet

  useraddress1:
    build: ./backend/address-service
    container_name: useraddress1
    environment:
      - DB_HOST=${Mysql_host}
      - DB_USER=${MySql_Db_User}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_Name=${MySql_Db}
    depends_on:
      - mysql
    networks:
      - webnet

  useraddress2:
    build: ./backend/address-service
    container_name: useraddress2
    environment:
      - DB_HOST=${Mysql_host}
      - DB_USER=${MySql_Db_User}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_Name=${MySql_Db}
    depends_on:
      - mysql
    networks:
      - webnet

  mysql:
    image: mysql:5.7
    container_name: mysql  
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webnet

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - mysql
      - usermobile1
      - usermobile2
      - useremail1
      - useremail2
      - useraddress1
      - useraddress2     
      - frontend
    networks:
      - webnet

networks:
  webnet:
